// Code generated by protoc-gen-go. DO NOT EDIT.
// source: yunpian.proto

package yunpian

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendResource struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Sid                  string   `protobuf:"bytes,2,opt,name=sid,proto3" json:"sid,omitempty"`
	Provider             string   `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	BizType              int32    `protobuf:"varint,4,opt,name=bizType,proto3" json:"bizType,omitempty"`
	Mobile               string   `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Content              string   `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Success              int64    `protobuf:"varint,7,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	Id                   int64    `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendResource) Reset()         { *m = SendResource{} }
func (m *SendResource) String() string { return proto.CompactTextString(m) }
func (*SendResource) ProtoMessage()    {}
func (*SendResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b76ee08c3871713, []int{0}
}

func (m *SendResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResource.Unmarshal(m, b)
}
func (m *SendResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResource.Marshal(b, m, deterministic)
}
func (m *SendResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResource.Merge(m, src)
}
func (m *SendResource) XXX_Size() int {
	return xxx_messageInfo_SendResource.Size(m)
}
func (m *SendResource) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResource.DiscardUnknown(m)
}

var xxx_messageInfo_SendResource proto.InternalMessageInfo

func (m *SendResource) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SendResource) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *SendResource) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *SendResource) GetBizType() int32 {
	if m != nil {
		return m.BizType
	}
	return 0
}

func (m *SendResource) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SendResource) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *SendResource) GetSuccess() int64 {
	if m != nil {
		return m.Success
	}
	return 0
}

func (m *SendResource) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SendResource) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MapType struct {
	Key                  int32    `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapType) Reset()         { *m = MapType{} }
func (m *MapType) String() string { return proto.CompactTextString(m) }
func (*MapType) ProtoMessage()    {}
func (*MapType) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b76ee08c3871713, []int{1}
}

func (m *MapType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapType.Unmarshal(m, b)
}
func (m *MapType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapType.Marshal(b, m, deterministic)
}
func (m *MapType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapType.Merge(m, src)
}
func (m *MapType) XXX_Size() int {
	return xxx_messageInfo_MapType.Size(m)
}
func (m *MapType) XXX_DiscardUnknown() {
	xxx_messageInfo_MapType.DiscardUnknown(m)
}

var xxx_messageInfo_MapType proto.InternalMessageInfo

func (m *MapType) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *MapType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BizTypeResponse struct {
	List                 []*MapType `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BizTypeResponse) Reset()         { *m = BizTypeResponse{} }
func (m *BizTypeResponse) String() string { return proto.CompactTextString(m) }
func (*BizTypeResponse) ProtoMessage()    {}
func (*BizTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b76ee08c3871713, []int{2}
}

func (m *BizTypeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BizTypeResponse.Unmarshal(m, b)
}
func (m *BizTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BizTypeResponse.Marshal(b, m, deterministic)
}
func (m *BizTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BizTypeResponse.Merge(m, src)
}
func (m *BizTypeResponse) XXX_Size() int {
	return xxx_messageInfo_BizTypeResponse.Size(m)
}
func (m *BizTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BizTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BizTypeResponse proto.InternalMessageInfo

func (m *BizTypeResponse) GetList() []*MapType {
	if m != nil {
		return m.List
	}
	return nil
}

type CodeResource struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	BizType              int32    `protobuf:"varint,2,opt,name=bizType,proto3" json:"bizType,omitempty"`
	Expires              int64    `protobuf:"varint,3,opt,name=expires,proto3" json:"expires,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodeResource) Reset()         { *m = CodeResource{} }
func (m *CodeResource) String() string { return proto.CompactTextString(m) }
func (*CodeResource) ProtoMessage()    {}
func (*CodeResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b76ee08c3871713, []int{3}
}

func (m *CodeResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeResource.Unmarshal(m, b)
}
func (m *CodeResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeResource.Marshal(b, m, deterministic)
}
func (m *CodeResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeResource.Merge(m, src)
}
func (m *CodeResource) XXX_Size() int {
	return xxx_messageInfo_CodeResource.Size(m)
}
func (m *CodeResource) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeResource.DiscardUnknown(m)
}

var xxx_messageInfo_CodeResource proto.InternalMessageInfo

func (m *CodeResource) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *CodeResource) GetBizType() int32 {
	if m != nil {
		return m.BizType
	}
	return 0
}

func (m *CodeResource) GetExpires() int64 {
	if m != nil {
		return m.Expires
	}
	return 0
}

type CodeResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ExpiresAt            string   `protobuf:"bytes,2,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodeResponse) Reset()         { *m = CodeResponse{} }
func (m *CodeResponse) String() string { return proto.CompactTextString(m) }
func (*CodeResponse) ProtoMessage()    {}
func (*CodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b76ee08c3871713, []int{4}
}

func (m *CodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeResponse.Unmarshal(m, b)
}
func (m *CodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeResponse.Marshal(b, m, deterministic)
}
func (m *CodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeResponse.Merge(m, src)
}
func (m *CodeResponse) XXX_Size() int {
	return xxx_messageInfo_CodeResponse.Size(m)
}
func (m *CodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CodeResponse proto.InternalMessageInfo

func (m *CodeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CodeResponse) GetExpiresAt() string {
	if m != nil {
		return m.ExpiresAt
	}
	return ""
}

func (m *CodeResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type ValidateRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	BizType              int32    `protobuf:"varint,2,opt,name=bizType,proto3" json:"bizType,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateRequest) Reset()         { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()    {}
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b76ee08c3871713, []int{5}
}

func (m *ValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRequest.Unmarshal(m, b)
}
func (m *ValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRequest.Marshal(b, m, deterministic)
}
func (m *ValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRequest.Merge(m, src)
}
func (m *ValidateRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRequest.Size(m)
}
func (m *ValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRequest proto.InternalMessageInfo

func (m *ValidateRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *ValidateRequest) GetBizType() int32 {
	if m != nil {
		return m.BizType
	}
	return 0
}

func (m *ValidateRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type ValidateResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateResponse) Reset()         { *m = ValidateResponse{} }
func (m *ValidateResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateResponse) ProtoMessage()    {}
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b76ee08c3871713, []int{6}
}

func (m *ValidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateResponse.Unmarshal(m, b)
}
func (m *ValidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateResponse.Marshal(b, m, deterministic)
}
func (m *ValidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateResponse.Merge(m, src)
}
func (m *ValidateResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateResponse.Size(m)
}
func (m *ValidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateResponse proto.InternalMessageInfo

func (m *ValidateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type EventResource struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	BizType              int32    `protobuf:"varint,2,opt,name=bizType,proto3" json:"bizType,omitempty"`
	TemplateId           int64    `protobuf:"varint,3,opt,name=templateId,proto3" json:"templateId,omitempty"`
	Value                []string `protobuf:"bytes,4,rep,name=value,proto3" json:"value,omitempty"`
	UserId               int64    `protobuf:"varint,5,opt,name=userId,proto3" json:"userId,omitempty"`
	Mode                 int32    `protobuf:"varint,6,opt,name=mode,proto3" json:"mode,omitempty"`
	Success              bool     `protobuf:"varint,7,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventResource) Reset()         { *m = EventResource{} }
func (m *EventResource) String() string { return proto.CompactTextString(m) }
func (*EventResource) ProtoMessage()    {}
func (*EventResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b76ee08c3871713, []int{7}
}

func (m *EventResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventResource.Unmarshal(m, b)
}
func (m *EventResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventResource.Marshal(b, m, deterministic)
}
func (m *EventResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventResource.Merge(m, src)
}
func (m *EventResource) XXX_Size() int {
	return xxx_messageInfo_EventResource.Size(m)
}
func (m *EventResource) XXX_DiscardUnknown() {
	xxx_messageInfo_EventResource.DiscardUnknown(m)
}

var xxx_messageInfo_EventResource proto.InternalMessageInfo

func (m *EventResource) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *EventResource) GetBizType() int32 {
	if m != nil {
		return m.BizType
	}
	return 0
}

func (m *EventResource) GetTemplateId() int64 {
	if m != nil {
		return m.TemplateId
	}
	return 0
}

func (m *EventResource) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *EventResource) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *EventResource) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *EventResource) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*SendResource)(nil), "yunpian.SendResource")
	proto.RegisterType((*MapType)(nil), "yunpian.MapType")
	proto.RegisterType((*BizTypeResponse)(nil), "yunpian.BizTypeResponse")
	proto.RegisterType((*CodeResource)(nil), "yunpian.CodeResource")
	proto.RegisterType((*CodeResponse)(nil), "yunpian.CodeResponse")
	proto.RegisterType((*ValidateRequest)(nil), "yunpian.ValidateRequest")
	proto.RegisterType((*ValidateResponse)(nil), "yunpian.ValidateResponse")
	proto.RegisterType((*EventResource)(nil), "yunpian.EventResource")
}

func init() { proto.RegisterFile("yunpian.proto", fileDescriptor_7b76ee08c3871713) }

var fileDescriptor_7b76ee08c3871713 = []byte{
	// 482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x8b, 0xd4, 0x40,
	0x10, 0x25, 0x93, 0xaf, 0x99, 0x72, 0xd7, 0x1d, 0x1a, 0x95, 0x36, 0x88, 0x84, 0xe0, 0x61, 0x0e,
	0xb2, 0xe0, 0x2a, 0xe8, 0x45, 0xc4, 0x15, 0x0f, 0x7b, 0xd0, 0x43, 0x2b, 0x0a, 0xde, 0x32, 0xe9,
	0x42, 0x1a, 0x33, 0xe9, 0x98, 0xee, 0x0c, 0x8e, 0xff, 0xcd, 0x7f, 0xe3, 0x6f, 0xf0, 0x2c, 0xdd,
	0xe9, 0x7c, 0xcc, 0xb8, 0x83, 0xa0, 0xb7, 0x7a, 0x55, 0x5d, 0x95, 0x57, 0xef, 0xd5, 0x0c, 0x9c,
	0xee, 0xda, 0xaa, 0x16, 0x79, 0x75, 0x5e, 0x37, 0x52, 0x4b, 0x12, 0x3b, 0x98, 0xfd, 0xf4, 0xe0,
	0xe4, 0x1d, 0x56, 0x9c, 0xa1, 0x92, 0x6d, 0x53, 0x20, 0xb9, 0x03, 0x51, 0xab, 0xb0, 0xb9, 0xe2,
	0xd4, 0x4b, 0xbd, 0x95, 0xcf, 0x1c, 0x22, 0x4b, 0xf0, 0x95, 0xe0, 0x74, 0x96, 0x7a, 0xab, 0x05,
	0x33, 0x21, 0x49, 0x60, 0x5e, 0x37, 0x72, 0x2b, 0x38, 0x36, 0xd4, 0xb7, 0xe9, 0x01, 0x13, 0x0a,
	0xf1, 0x5a, 0x7c, 0x7f, 0xbf, 0xab, 0x91, 0x06, 0xa9, 0xb7, 0x0a, 0x59, 0x0f, 0xcd, 0xfc, 0x8d,
	0x5c, 0x8b, 0x12, 0x69, 0x68, 0x7b, 0x1c, 0x32, 0x1d, 0x85, 0xac, 0x34, 0x56, 0x9a, 0x46, 0xb6,
	0xd0, 0x43, 0x53, 0x51, 0x6d, 0x51, 0xa0, 0x52, 0x34, 0xb6, 0x94, 0x7a, 0x68, 0x2a, 0x1b, 0x54,
	0x2a, 0xff, 0x8c, 0x74, 0xde, 0xf5, 0x38, 0x48, 0x6e, 0xc2, 0x4c, 0x70, 0xba, 0xb0, 0xcf, 0x67,
	0x82, 0x67, 0x8f, 0x20, 0x7e, 0x93, 0xd7, 0x96, 0xc0, 0x12, 0xfc, 0x2f, 0xb8, 0xb3, 0xdb, 0x85,
	0xcc, 0x84, 0xe4, 0x16, 0x84, 0xdb, 0xbc, 0x6c, 0xd1, 0x2d, 0xd7, 0x81, 0xec, 0x29, 0x9c, 0x5d,
	0x76, 0x9c, 0x19, 0xaa, 0x5a, 0x56, 0x0a, 0xc9, 0x03, 0x08, 0x4a, 0xa1, 0x34, 0xf5, 0x52, 0x7f,
	0x75, 0xe3, 0x62, 0x79, 0xde, 0x6b, 0xea, 0x46, 0x33, 0x5b, 0xcd, 0x3e, 0xc1, 0xc9, 0x2b, 0xc9,
	0x71, 0xaa, 0xa8, 0xdb, 0xd8, 0x3b, 0xdc, 0xb8, 0xd7, 0x68, 0xb6, 0xaf, 0x11, 0x85, 0x18, 0xbf,
	0xd5, 0xa2, 0x41, 0x65, 0x85, 0xf5, 0x59, 0x0f, 0x27, 0xb3, 0x3b, 0x46, 0x13, 0x6d, 0xcc, 0xf0,
	0xf9, 0xa8, 0xcd, 0x3d, 0x58, 0xb8, 0xa6, 0x97, 0xda, 0x2d, 0x36, 0x26, 0x08, 0x81, 0xa0, 0x90,
	0x1c, 0x9d, 0x6f, 0x36, 0xce, 0x3e, 0xc2, 0xd9, 0x87, 0xbc, 0x14, 0x3c, 0xd7, 0xc8, 0xf0, 0x6b,
	0x8b, 0x4a, 0xff, 0x03, 0xf5, 0xeb, 0x06, 0x3f, 0x84, 0xe5, 0x38, 0xf8, 0x6f, 0xc4, 0xb3, 0x1f,
	0x1e, 0x9c, 0xbe, 0xde, 0x62, 0xa5, 0xff, 0x43, 0xc0, 0xfb, 0x00, 0x1a, 0x37, 0x75, 0x99, 0x6b,
	0xbc, 0xe2, 0x4e, 0xc3, 0x49, 0x66, 0x74, 0x3c, 0x48, 0xfd, 0xc1, 0xf1, 0xc9, 0xe9, 0x87, 0x7b,
	0xa7, 0x4f, 0x20, 0xd8, 0x98, 0x9d, 0x22, 0xfb, 0x11, 0x1b, 0x1f, 0x1e, 0xe5, 0xc8, 0xff, 0xe2,
	0x97, 0x07, 0x81, 0xf9, 0x45, 0x91, 0xe7, 0x10, 0x5f, 0xf6, 0x86, 0x0e, 0xa7, 0x72, 0x70, 0x52,
	0xc9, 0xd1, 0x0a, 0x79, 0x02, 0x81, 0xb1, 0x9a, 0xdc, 0x1e, 0x5e, 0x4c, 0xaf, 0x2a, 0xf9, 0x23,
	0xdd, 0x75, 0xbd, 0x80, 0x79, 0xaf, 0xf5, 0xe4, 0xab, 0x07, 0xbe, 0x26, 0x77, 0xaf, 0xa9, 0xb8,
	0x01, 0xcf, 0x20, 0x7a, 0x2b, 0xb5, 0x30, 0xb2, 0x0f, 0x8f, 0xf6, 0xec, 0x48, 0x8e, 0xe4, 0xd7,
	0x91, 0xfd, 0x6b, 0x79, 0xfc, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x62, 0x3f, 0x28, 0x6b, 0x04,
	0x00, 0x00,
}
