// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sms.proto

package sms

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SmsStruct struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Sid                  string   `protobuf:"bytes,2,opt,name=sid,proto3" json:"sid,omitempty"`
	Provider             string   `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	BizType              int32    `protobuf:"varint,4,opt,name=bizType,proto3" json:"bizType,omitempty"`
	Mobile               string   `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Content              string   `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Success              int64    `protobuf:"varint,7,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	Id                   int64    `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
	Mode                 int32    `protobuf:"varint,10,opt,name=mode,proto3" json:"mode,omitempty"`
	Sign                 string   `protobuf:"bytes,11,opt,name=sign,proto3" json:"sign,omitempty"`
	ExpiresAt            string   `protobuf:"bytes,12,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsStruct) Reset()         { *m = SmsStruct{} }
func (m *SmsStruct) String() string { return proto.CompactTextString(m) }
func (*SmsStruct) ProtoMessage()    {}
func (*SmsStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8d8bdc537111860, []int{0}
}

func (m *SmsStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsStruct.Unmarshal(m, b)
}
func (m *SmsStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsStruct.Marshal(b, m, deterministic)
}
func (m *SmsStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsStruct.Merge(m, src)
}
func (m *SmsStruct) XXX_Size() int {
	return xxx_messageInfo_SmsStruct.Size(m)
}
func (m *SmsStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsStruct.DiscardUnknown(m)
}

var xxx_messageInfo_SmsStruct proto.InternalMessageInfo

func (m *SmsStruct) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SmsStruct) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *SmsStruct) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *SmsStruct) GetBizType() int32 {
	if m != nil {
		return m.BizType
	}
	return 0
}

func (m *SmsStruct) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SmsStruct) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *SmsStruct) GetSuccess() int64 {
	if m != nil {
		return m.Success
	}
	return 0
}

func (m *SmsStruct) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SmsStruct) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SmsStruct) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *SmsStruct) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *SmsStruct) GetExpiresAt() string {
	if m != nil {
		return m.ExpiresAt
	}
	return ""
}

type SendPage struct {
	Data                 []*SmsStruct `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SendPage) Reset()         { *m = SendPage{} }
func (m *SendPage) String() string { return proto.CompactTextString(m) }
func (*SendPage) ProtoMessage()    {}
func (*SendPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8d8bdc537111860, []int{1}
}

func (m *SendPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPage.Unmarshal(m, b)
}
func (m *SendPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPage.Marshal(b, m, deterministic)
}
func (m *SendPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPage.Merge(m, src)
}
func (m *SendPage) XXX_Size() int {
	return xxx_messageInfo_SendPage.Size(m)
}
func (m *SendPage) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPage.DiscardUnknown(m)
}

var xxx_messageInfo_SendPage proto.InternalMessageInfo

func (m *SendPage) GetData() []*SmsStruct {
	if m != nil {
		return m.Data
	}
	return nil
}

// *************  短信模板 ************************ //
type TemplatePage struct {
	Data                 []*SmsStruct `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TemplatePage) Reset()         { *m = TemplatePage{} }
func (m *TemplatePage) String() string { return proto.CompactTextString(m) }
func (*TemplatePage) ProtoMessage()    {}
func (*TemplatePage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8d8bdc537111860, []int{2}
}

func (m *TemplatePage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplatePage.Unmarshal(m, b)
}
func (m *TemplatePage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplatePage.Marshal(b, m, deterministic)
}
func (m *TemplatePage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplatePage.Merge(m, src)
}
func (m *TemplatePage) XXX_Size() int {
	return xxx_messageInfo_TemplatePage.Size(m)
}
func (m *TemplatePage) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplatePage.DiscardUnknown(m)
}

var xxx_messageInfo_TemplatePage proto.InternalMessageInfo

func (m *TemplatePage) GetData() []*SmsStruct {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8d8bdc537111860, []int{3}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *ListRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type ListResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8d8bdc537111860, []int{4}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CreateTempRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTempRequest) Reset()         { *m = CreateTempRequest{} }
func (m *CreateTempRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTempRequest) ProtoMessage()    {}
func (*CreateTempRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8d8bdc537111860, []int{5}
}

func (m *CreateTempRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTempRequest.Unmarshal(m, b)
}
func (m *CreateTempRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTempRequest.Marshal(b, m, deterministic)
}
func (m *CreateTempRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTempRequest.Merge(m, src)
}
func (m *CreateTempRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTempRequest.Size(m)
}
func (m *CreateTempRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTempRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTempRequest proto.InternalMessageInfo

type CreateTempResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTempResponse) Reset()         { *m = CreateTempResponse{} }
func (m *CreateTempResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTempResponse) ProtoMessage()    {}
func (*CreateTempResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8d8bdc537111860, []int{6}
}

func (m *CreateTempResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTempResponse.Unmarshal(m, b)
}
func (m *CreateTempResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTempResponse.Marshal(b, m, deterministic)
}
func (m *CreateTempResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTempResponse.Merge(m, src)
}
func (m *CreateTempResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTempResponse.Size(m)
}
func (m *CreateTempResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTempResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTempResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SmsStruct)(nil), "sms.SmsStruct")
	proto.RegisterType((*SendPage)(nil), "sms.SendPage")
	proto.RegisterType((*TemplatePage)(nil), "sms.TemplatePage")
	proto.RegisterType((*ListRequest)(nil), "sms.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "sms.ListResponse")
	proto.RegisterType((*CreateTempRequest)(nil), "sms.CreateTempRequest")
	proto.RegisterType((*CreateTempResponse)(nil), "sms.CreateTempResponse")
}

func init() { proto.RegisterFile("sms.proto", fileDescriptor_c8d8bdc537111860) }

var fileDescriptor_c8d8bdc537111860 = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x63, 0x37, 0xb5, 0x27, 0xa1, 0x6a, 0x07, 0x54, 0x56, 0x16, 0x87, 0xc8, 0x27, 0x0b,
	0xa4, 0x1c, 0x02, 0x97, 0x1e, 0x11, 0x27, 0x24, 0x0e, 0xc8, 0xe9, 0x1f, 0x70, 0xbc, 0xa3, 0x6a,
	0xa5, 0xae, 0x6d, 0x3c, 0x1b, 0x04, 0xfc, 0x21, 0x7e, 0x23, 0x37, 0xb4, 0xb3, 0x4e, 0xea, 0x34,
	0x97, 0xde, 0xe6, 0xbd, 0xb7, 0x6f, 0x3e, 0x9e, 0x65, 0xc8, 0xd8, 0xf2, 0xba, 0x1f, 0x3a, 0xd7,
	0x61, 0xcc, 0x96, 0x8b, 0xbf, 0x33, 0xc8, 0xb6, 0x96, 0xb7, 0x6e, 0xd8, 0x37, 0x0e, 0x6f, 0x61,
	0xbe, 0x67, 0x1a, 0xbe, 0x6a, 0x15, 0xad, 0xa2, 0x32, 0xae, 0x46, 0x84, 0xd7, 0x10, 0xb3, 0xd1,
	0x6a, 0xb6, 0x8a, 0xca, 0xac, 0xf2, 0x25, 0xe6, 0x90, 0xf6, 0x43, 0xf7, 0xd3, 0x68, 0x1a, 0x54,
	0x2c, 0xf4, 0x11, 0xa3, 0x82, 0xcb, 0x9d, 0xf9, 0x73, 0xff, 0xbb, 0x27, 0x95, 0xac, 0xa2, 0xf2,
	0xa2, 0x3a, 0x40, 0xdf, 0xdf, 0x76, 0x3b, 0xf3, 0x48, 0xea, 0x42, 0x3c, 0x23, 0xf2, 0x8e, 0xa6,
	0x6b, 0x1d, 0xb5, 0x4e, 0xcd, 0x45, 0x38, 0x40, 0xaf, 0xf0, 0xbe, 0x69, 0x88, 0x59, 0x5d, 0xca,
	0x4a, 0x07, 0xe8, 0x15, 0x4b, 0xcc, 0xf5, 0x03, 0xa9, 0x34, 0x78, 0x46, 0x88, 0x57, 0x30, 0x33,
	0x5a, 0x65, 0xf2, 0x7c, 0x66, 0x34, 0x22, 0x24, 0xb6, 0xd3, 0xa4, 0x40, 0x96, 0x91, 0xda, 0x73,
	0x6c, 0x1e, 0x5a, 0xb5, 0x10, 0xab, 0xd4, 0xf8, 0x0e, 0x32, 0xfa, 0xd5, 0x9b, 0x81, 0xf8, 0xb3,
	0x53, 0x4b, 0x11, 0x9e, 0x88, 0x62, 0x0d, 0xe9, 0x96, 0x5a, 0xfd, 0xdd, 0x4f, 0x28, 0x20, 0xd1,
	0xb5, 0xab, 0x55, 0xb4, 0x8a, 0xcb, 0xc5, 0xe6, 0x6a, 0xed, 0x43, 0x3d, 0xa6, 0x58, 0x89, 0x56,
	0x6c, 0x60, 0x79, 0x4f, 0xb6, 0x7f, 0xac, 0x1d, 0xbd, 0xd8, 0x73, 0x07, 0x8b, 0x6f, 0x86, 0x5d,
	0x45, 0x3f, 0xf6, 0xc4, 0x6e, 0x12, 0x57, 0x74, 0x12, 0x17, 0x42, 0xd2, 0xf8, 0x83, 0xc2, 0xf7,
	0x90, 0xba, 0x28, 0x61, 0x19, 0xac, 0xdc, 0x77, 0x2d, 0xd3, 0x34, 0x38, 0x6f, 0x4e, 0x8f, 0xc1,
	0x15, 0xaf, 0xe1, 0xe6, 0xcb, 0x40, 0xb5, 0x23, 0xbf, 0xde, 0x38, 0xaa, 0x78, 0x03, 0x38, 0x25,
	0x43, 0x93, 0xcd, 0xbf, 0x08, 0xe2, 0xad, 0x65, 0x2c, 0xc3, 0xed, 0x7e, 0x00, 0xbe, 0x0a, 0x9b,
	0x8f, 0x51, 0xe4, 0xa7, 0x10, 0x3f, 0x3d, 0x5d, 0x2d, 0xaf, 0x6f, 0x44, 0x9e, 0x06, 0x91, 0x9f,
	0x53, 0xf8, 0x1e, 0xd2, 0x03, 0xc6, 0x67, 0xc9, 0xe4, 0xcf, 0x30, 0x7e, 0x80, 0x44, 0x3a, 0x5f,
	0x0b, 0x3f, 0x89, 0x6b, 0x6c, 0x7c, 0x92, 0xc2, 0x1d, 0xcc, 0xc3, 0x59, 0x78, 0x2b, 0xe2, 0xd9,
	0xe1, 0xf9, 0xdb, 0x33, 0x3e, 0x58, 0x77, 0x73, 0xf9, 0x4b, 0x3e, 0xfe, 0x0f, 0x00, 0x00, 0xff,
	0xff, 0x1e, 0xc6, 0xf0, 0x3a, 0x32, 0x03, 0x00, 0x00,
}
